In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [19]:
sales = pd.read_csv("samplesuperstore.csv")
sales.head()
sales.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [13]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  str
 6   Customer Name   10194 non-null  str
 7   Segment         10194 non-null  str
 8   Country/Region  10194 non-null  str
 9   City            10194 non-null  str
 10  State/Province  10194 non-null  str
 11  Postal Code     10194 non-null  str
 12  Region          10194 non-null  str
 13  Product ID      10194 non-null  str
 14  Category        10194 non-null  str
 15  Sub-Category    10194 non-null  str
 16  Product Name    10194 non-null  str
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), str(16)
memory usage: 1.6 MB

In [14]:
sales.describe()

             Row ID         Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.225854      3.791838      0.155385     28.673417
std     2942.898656    619.906839      2.228317      0.206249    232.465115
min        1.000000      0.444000      1.000000      0.000000  -6599.978000
25%     2549.250000     17.220000      2.000000      0.000000      1.760800
50%     5097.500000     53.910000      3.000000      0.200000      8.690000
75%     7645.750000    209.500000      5.000000      0.200000     29.297925
max    10194.000000  22638.480000     14.000000      0.800000   8399.976000

In [15]:
sales.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID           str
Customer Name         str
Segment               str
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Region                str
Product ID            str
Category              str
Sub-Category          str
Product Name          str
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [16]:
sales.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [ ]:
sales.isnull().sum()

In [ ]:
sales.duplicated().sum()

In [23]:
sales.rename(columns={"Country/Region": "Country"}, inplace=True)
sales.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [24]:
sales.columns.tolist()
sales.columns = sales.columns.str.strip()
sales.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State/Province',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [ ]:
high5_sales = sales.nlargest(5,"Sales")
high5_sales[["Country","Sales"]]

            Country      Sales     Profit
226   United States  22638.480 -1811.0784
5894  United States  17499.950  8399.9760
7255  United States  13999.960  6719.9808
9171  United States  11199.968  3919.9888
9517  United States  10499.970  5039.9856

In [ ]:
least5_sales = sales.nsmallest(5,"Sales")
least5_sales[["Country","Sales"]]

            Country  Sales
7930  United States  0.444
7087  United States  0.556
5074  United States  0.836
286   United States  0.852
1227  United States  0.876

In [33]:
high5_prof = sales.nlargest(5,"Profit")
high5_prof[["Country","Profit"]]

            Country     Profit
5894  United States  8399.9760
7255  United States  6719.9808
9517  United States  5039.9856
6674  United States  4946.3700
1203  United States  4630.4755

In [34]:
least5_prof = sales.nsmallest(5,"Profit")
least5_prof[["Country","Profit"]]

            Country     Profit
6398  United States -6599.9780
9318  United States -3839.9904
821   United States -3701.8928
7441  United States -3399.9800
9845  United States -2929.4845

In [25]:
product_total = sales.groupby(["Country","Region","Product Name"])["Sales"].sum()
product_total

Country        Region   Product Name
Canada         Central  Eldon 400 Class Desk Accessories, Black Carbon                                                          29.992
                        GBC Twin Loop Wire Binding Elements                                                                    127.954
                        Perma STOR-ALL Hanging File Box, 13 1/8"W x 12 1/4"D x 10 1/2"H                                         52.786
                        SAFCO Arco Folding Chair                                                                               710.496
                        Wilson Jones Active Use Binders                                                                        872.380
                                                                                                                                ...
United States  West     iKross Bluetooth Portable Keyboard + Cell Phone Stand Holder + Brush for Apple iPhone 5S 5C 5, 4S 4    100.560
                        iOttie HLCRIO102 Car Mount                                                                              31.984
                        iOttie XL Car Mount                                                                                     79.960
                        invisibleSHIELD by ZAGG Smudge-Free Screen Protector                                                   158.312
                        netTALK DUO VoIP Telephone Service                                                                     839.840
Name: Sales, Length: 5326, dtype: float64

In [26]:
city_avg = sales.groupby("City")["Sales"].mean()
city_avg

City
Aberdeen        25.500000
Abilene          1.392000
Akron          129.999333
Albuquerque    158.582857
Alexandria     344.973125
                  ...
Woonsocket      48.887500
Yonkers        510.511067
York           163.595600
Yucaipa         50.800000
Yuma           210.216250
Name: Sales, Length: 542, dtype: float64